version: '3.3'

services:

  mysql:
    build:
      context: mysql
    volumes:
      - mysql-stweb-db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mariadb

    networks:
      stnet:
        ipv4_address: 172.10.1.2


        #  rabbitmq:
#    build:
#      context: rabbitmq
#    environment:
#      RABBITMQ_DEFAULT_USER: rabbituser
#      RABBITMQ_DEFAULT_PASS: rabbitpass
#      RABBITMQ_DEFAULT_VHOST: rabbitmq

  django:

    build:
      context: django

    volumes:
      - ./project-data:/usr/src/app/
    ports:
      - "8000:8000"

    entrypoint: 
      - /bin/sh
      - /usr/src/app/django/startup.sh

    depends_on:
      - mysql
 #     - rabbitmq
    networks:
      stnet:
        ipv4_address: 172.10.1.3


  angular:
    build:
      context: angular
    volumes:
      - ./project-data:/usr/src/app/
    ports:
      - "4200:4200"
    entrypoint:
      - /bin/sh 
      - /usr/src/app/angular/startup.sh

    networks:
      stnet:
        ipv4_address: 172.10.1.4

  nginx:
    build:
      context: nginx
    volumes:
      - ./project-data:/usr/src/app/
    ports:
      - "80:80"
    depends_on:
      - django

    networks:
      stnet:
        ipv4_address: 172.10.1.5

volumes:
  mysql-stweb-db: 
    external : yes    

networks:
  stnet:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16