# Generated by Django 3.1.5 on 2021-01-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='group',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='token',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
