# Generated by Django 3.1.5 on 2021-01-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_auto_20210111_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
