# Generated by Django 3.1.5 on 2021-01-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0003_auto_20210112_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdb',
            name='username',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
