# Generated by Django 3.1.5 on 2021-01-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0004_auto_20210112_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
